In [1]:
import pandas as pd
import os

In [2]:
BASE_PATH = r"C:\ml 2026\dataset"

TRAIN_PATH = os.path.join(BASE_PATH, "train")
TEST_PATH = os.path.join(BASE_PATH, "test")

In [3]:
train_s1 = pd.read_csv(
    os.path.join(TRAIN_PATH, "train_source1.tsv"),
    sep="\t"
)

train_s2 = pd.read_csv(
    os.path.join(TRAIN_PATH, "train_source2.tsv"),
    sep="\t"
)

train_s3 = pd.read_csv(
    os.path.join(TRAIN_PATH, "train_source3.tsv"),
    sep="\t"
)

ground_truth = pd.read_csv(
    os.path.join(TRAIN_PATH, "train_ground_truth.tsv"),
    sep="\t"
)

In [4]:
test_s1 = pd.read_csv(
    os.path.join(TEST_PATH, "test_source1.tsv"),
    sep="\t"
)

test_s2 = pd.read_csv(
    os.path.join(TEST_PATH, "test_source2.tsv"),
    sep="\t"
)

test_s3 = pd.read_csv(
    os.path.join(TEST_PATH, "test_source3.tsv"),
    sep="\t"
)

In [5]:
print("TRAINING DATA")
print("Source 1:", train_s1.shape)
print("Source 2:", train_s2.shape)
print("Source 3:", train_s3.shape)
print("Ground Truth:", ground_truth.shape)

print("\nTEST DATA")
print("Source 1:", test_s1.shape)
print("Source 2:", test_s2.shape)
print("Source 3:", test_s3.shape)

TRAINING DATA
Source 1: (2206821, 4)
Source 2: (5034616, 4)
Source 3: (5285603, 4)
Ground Truth: (2206821, 2)

TEST DATA
Source 1: (1732544, 4)
Source 2: (4887273, 4)
Source 3: (5082316, 4)

In [6]:
print("TRAIN S1:")
print(train_s1.columns.tolist())

print("\nTRAIN S2:")
print(train_s2.columns.tolist())

print("\nTRAIN S3:")
print(train_s3.columns.tolist())

print("\nGROUND TRUTH:")
print(ground_truth.columns.tolist())

TRAIN S1:
['entity_id', 'business_name', 'business_address', 'country']

TRAIN S2:
['entity_id', 'business_name', 'business_address', 'country']

TRAIN S3:
['entity_id', 'business_name', 'business_address', 'country']

GROUND TRUTH:
['source1_entity_id', 'matched_entity_ids']

In [7]:
print("TRAIN SOURCE 1")
display(train_s1.head())

print("TRAIN SOURCE 2")
display(train_s2.head())

print("TRAIN SOURCE 3")
display(train_s3.head())

print("GROUND TRUTH")
display(ground_truth.head())

TRAIN SOURCE 1

,entity_id,business_name,business_address,country
0,S1-925783039,Orelee's Barbershop,"1795 Westchester Drive, High Point, NC",US
1,S1-773889195,Prime Money,"17560 Ellis Road, Tahlequah, OK",US
2,S1-377745466,B+ Retail Inc,"1712 Montebello Avenue, Phoenix, AZ",US
3,S1-133037285,Christ Chapel,"2100 Cameron Drive, Unit APARTMENT G, Dundalk, MD",US
4,S1-755362802,Prabhav Business Center,"797, Lake Town Block A, Kolkata, Howrah, West ...",India

TRAIN SOURCE 2

,entity_id,business_name,business_address,country
0,S2-166376419,राम मार्केटिंग प्राइवेट लिमिटेड,"KH NO. -570/13, NEW DELHI, WEST DELHI, Delhi",India
1,S2-764573417,-- Holloway Peak Inc Seafood,"105 ELM ST, MORGANTON, NC",US
2,S2-639257739,आदित्य प्रॉपर्टीज एलएलपी,"G-3/571, GULMOHAR COLONY, BHOPAL, Madhya Pradesh",India
3,S2-163963287,Summit Inc,"GREENSBORO, NC, 19 1/2 STARDUST TRAIL",US
4,S2-49942811,Delta Tetlecommunication Inc,"914 PIERPONT AVE, CLEVELAND, OH",US

TRAIN SOURCE 3

,entity_id,business_name,business_address,country
0,S3-202863386,wilfordhancock.com,"Mack Rd, Haltom City, Texas",US
1,S3-859268022,International South Consultants Private Ltd,NaN,India
2,S3-22467283,LLC Moncada Léarning Center,"5780 Fawn Ct, Fort Worth, Texas",US
3,S3-671162755,Moyna's Coffee,"1 Ivanhoe Ave, PO Box 6009, Cincinnati, Ohio",US
4,S3-960981775,Pvt. EFS Print Ventures Ltd.,"Door No 183, 41St Cross, 22Nd Main 9Th Block J...",India

GROUND TRUTH

  source1_entity_id                                 matched_entity_ids
0         S1-965667  S2-681193310,S2-743505751,S3-775321672,S3-1129...
1       S1-55344266  S2-249013014,S2-197070651,S3-478195123,S3-3843...
2      S1-343815751             S2-790675320,S2-479876582,S3-878454467
3      S1-656753428              S2-153058913,S2-24659151,S3-679606215
4      S1-102811957  S2-478959098,S2-553508714,S2-625774905,S3-7280...

In [8]:
print("SOURCE 1")
print(train_s1.isnull().sum())

print("\nSOURCE 2")
print(train_s2.isnull().sum())

print("\nSOURCE 3")
print(train_s3.isnull().sum())

print("\nGROUND TRUTH")
print(ground_truth.isnull().sum())

SOURCE 1
entity_id           0
business_name       0
business_address    0
country             0
dtype: int64

SOURCE 2
entity_id                0
business_name            2
business_address    168967
country                  0
dtype: int64

SOURCE 3
entity_id                0
business_name           13
business_address    175916
country                  0
dtype: int64

GROUND TRUTH
source1_entity_id          0
matched_entity_ids    123247
dtype: int64

In [9]:
print("SOURCE 1 COUNTRIES")
print(train_s1["country"].value_counts())

print("\nSOURCE 2 COUNTRIES")
print(train_s2["country"].value_counts())

print("\nSOURCE 3 COUNTRIES")
print(train_s3["country"].value_counts())

SOURCE 1 COUNTRIES
country
US       1323633
India     883188
Name: count, dtype: int64

SOURCE 2 COUNTRIES
country
US       3016817
India    2017799
Name: count, dtype: int64

SOURCE 3 COUNTRIES
country
US       3170056
India    2115547
Name: count, dtype: int64

In [10]:
print("Duplicate IDs")

print(
    "S1:",
    train_s1["entity_id"].duplicated().sum()
)

print(
    "S2:",
    train_s2["entity_id"].duplicated().sum()
)

print(
    "S3:",
    train_s3["entity_id"].duplicated().sum()
)

Duplicate IDs
S1: 0
S2: 0
S3: 0

In [12]:
def count_matches(value):

    if pd.isna(value):
        return 0

    value = str(value).strip()

    if value == "":
        return 0

    return len(value.split(","))
ground_truth["match_count"] = (
    ground_truth["matched_entity_ids"]
    .apply(count_matches)
)
print(
    ground_truth["match_count"]
    .value_counts()
    .sort_index()
)
print(
    "Zero matches:",
    (ground_truth["match_count"] == 0).sum()
)

print(
    "One match:",
    (ground_truth["match_count"] == 1).sum()
)

print(
    "Multiple matches:",
    (ground_truth["match_count"] > 1).sum()
)

match_count
0     123247
1     119157
2     375212
3     530841
4     484115
5     321957
6     164868
7      63968
8      18680
9       4205
10       534
11        37
Name: count, dtype: int64
Zero matches: 123247
One match: 119157
Multiple matches: 1964417